ALTER TABLE xp_wakander
ADD COLUMN sab_teorico INT NOT NULL DEFAULT 0,
ADD COLUMN sab_processo INT NOT NULL DEFAULT 0,
ADD COLUMN sab_know_how INT NOT NULL DEFAULT 0,
ADD COLUMN sab_comportamental INT NOT NULL DEFAULT 0,
ADD COLUMN sab_criativo INT NOT NULL DEFAULT 0;
